# Setup
version_name: "0"
out_dir: "../500_edge/"

# Database
train_db_name: NYUD
val_db_name: NYUD
trBatch: 4
valBatch: 6
nworkers: 2
ignore_index: 255
task_files:
  depth: 500_500_500/random700_200_1699297038_0.txt

# Optimizer and scheduler
intermediate_supervision: False
val_interval: 1000
epochs: 999999
max_iter: 40000
optimizer: adam
optimizer_kwargs:
   lr: 0.00001
   weight_decay: 1.e-6
scheduler: poly
grad_clip_param: {'max_norm': 10, 'norm_type': 2}
ignore_invalid_area_depth: True

# Model
model: TaskPrompter
backbone: TaskPrompter_vitL
head:  conv
embed_dim: 768
final_embed_dim: 768
prompt_len: 1
chan_nheads: 16
use_ctr: False

# Tasks
task_dictionary:
   include_semseg: False
   include_depth: False
   include_edge: True
   include_normals: False
   edge_w: 0.95

# Loss kwargs
loss_kwargs:
   loss_weights:
       edge: 50.0
