# Setup
version_name: 6
out_dir: "../43_142_142_142_142"

# Database
train_db_name: NYUD
val_db_name: NYUD
trBatch: 4
valBatch: 6
nworkers: 2
ignore_index: 255
task_files:
  semseg: 43_142_142_142/random243_200_1699297026_6.txt
  depth: 43_142_142_142/random342_200_1699297029_6.txt
  normals: 43_142_142_142/random342_200_1699297033_6.txt
  edge: 43_142_142_142/random342_200_1699297038_6.txt

# Optimizer and scheduler
intermediate_supervision: False
val_interval: 1000
epochs: 999999
max_iter: 40000
optimizer: adam
optimizer_kwargs:
   lr: 0.00001
   weight_decay: 1.e-6
scheduler: poly
grad_clip_param: {'max_norm': 10, 'norm_type': 2}
ignore_invalid_area_depth: True

# Model
model: TaskPrompter
backbone: TaskPrompter_vitL
head:  conv
embed_dim: 768
final_embed_dim: 768
prompt_len: 1
chan_nheads: 16
use_ctr: False

# Tasks
task_dictionary:
   include_semseg: True
   include_depth: True
   include_edge: True
   include_normals: True
   edge_w: 0.95

# Loss kwargs
loss_kwargs:
   loss_weights:
       semseg: 1.0
       depth: 1.0
       normals: 10
       edge: 50.0
